### PR TITLE
feat: adds `region` settings used to configure the instance template

### PR DESCRIPTION
**Pull request by viniciusdsmello**
This Pull Request adds the variable `region` that will be used to configure the instance template.

The instance Template module has a variable `region`. However, the bastion module does not allow the developers to pass its value [1]. Without it, when trying to deploy a bastion host, the module fails when trying to create the instance template.

## References
1. https://github.com/terraform-google-modules/terraform-google-vm/blob/01f273d4e9fc5481602e9fe2ed5e9fbc857bc4b4/modules/instance_template/variables.tf#L77

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@viniciusdsmello
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=autogen' '--exclude=*.tfvars' '--exclude=*metadata.yaml' /workspace/README.md /tmp/tmp.f4n5dW5YI6/generate_docs/workspace/README.md
94a95
> | region | The region where the bastion instance template will live | `string` | `"us-central1"` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@viniciusdsmello
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@viniciusdsmello
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@viniciusdsmello
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @viniciusdsmello!

**Pull request merged**
