### PR TITLE
feat: Updated changelog to pull in new fixes

### PR DESCRIPTION
**Pull request by onetwopunch**
Release 2.6.0

### CODE REVIEW

**Comment by morgante** [comment]
@onetwopunch You should switch to using release-please.

**Comment by onetwopunch** [comment]
@morgante Yeah this is because I forgot to update the most recent merges with conventional commits so release please didn't pick them up.

**Comment by morgante** [comment]
Ok, but this changelog has 2.6.0 listed twice.

For the future if you forget to do a conventional commit you should just edit the commit history with `git rebase`.

**Comment by onetwopunch** [comment]
@morgante Thanks for pointing that out. Not sure how that got there. I'll clean this up thanks

**Pull request closed without merging**
