### PR TITLE
Fix: Update Debian Image to 12

### PR DESCRIPTION
**Pull request by RoseSecurity**
# What and Why

- Update default `machine_type` to `debian-12`
- Debian 12.0 was initially released on June 10th, 2023

### CODE REVIEW

**Comment by RoseSecurity** [comment]
@Djabx Any thoughts on this?

**Comment by Djabx** [comment]
@RoseSecurity Hi,
No issue for me: I'm setting the variable on my side.

But I'm just a contributor, not a maintainer :P

**Comment by apeabody** [comment]
Thanks for the contribution @RoseSecurity!

It looks like one of the commits used an email address not covered by the CLA.

**Comment by RoseSecurity** [comment]
> Thanks for the contribution @RoseSecurity!
> 
> It looks like one of the commits used an email address not covered by the CLA.

No worries! Just signed the CLA with that email address as well.

**Comment by apeabody** [comment]
> > Thanks for the contribution @RoseSecurity!
> > It looks like one of the commits used an email address not covered by the CLA.
> 
> No worries! Just signed the CLA with that email address as well. @apeabody

Thanks! - That check is now green.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @RoseSecurity!

**Pull request merged**
