### PR TITLE
Expose disk size and type. Default 10gb pd-standard

### PR DESCRIPTION
**Pull request by c0ffeec0der**
Expose disk size and type. Default 100gb pd-standard

### CODE REVIEW

**Comment by onetwopunch** [comment]
Hi @c0ffeec0der thanks for the commit! Please make sure to run `terraform fmt` and `make docker_generate_docs`. You can validate that linting passed by running `make docker_test_lint`

**Comment by c0ffeec0der** [comment]
Hello @onetwopunch 

I have run all three commands and there are two errors on linting test:

Error: The following tests have failed: check_whitespace check_headers
make: *** [Makefile:70: docker_test_lint] Error 2

Let me know if there is anything else

Linting test result:

Checking for documentation generation
Checking for trailing whitespace
Checking for missing newline at end of file
Running shellcheck
Checking file headers
Running flake8
Running terraform fmt
Running terraform validate
terraform_validate .
Success! The configuration is valid.

terraform_validate ./examples/bastion_group
Success! The configuration is valid.

terraform_validate ./examples/iap_tunneling
Success! The configuration is valid.

terraform_validate ./examples/simple_example
Success! The configuration is valid.

terraform_validate ./examples/two_service_example
Success! The configuration is valid.

terraform_validate ./modules/bastion-group
Success! The configuration is valid.

terraform_validate ./modules/iap-tunneling
Success! The configuration is valid.

terraform_validate ./test/fixtures/bastion_group
Success! The configuration is valid.

terraform_validate ./test/fixtures/iap_tunneling
Success! The configuration is valid.

terraform_validate ./test/fixtures/simple
Success! The configuration is valid.

terraform_validate ./test/setup
Success! The configuration is valid.

Error: The following tests have failed: check_whitespace check_headers
make: *** [Makefile:70: docker_test_lint] Error 2

**Comment by bharathkkb** [comment]
@c0ffeec0der lint checks seems to have passed on our side, so this should be good. On occasion due to other gitignored files present in the directory (.DS_STORE for instance), lint checks may fail locally.

**Comment by c0ffeec0der** [comment]
@bharathkkb okay, got it! so what's left is for @onetwopunch to approve for merging then

**Comment by onetwopunch** [comment]
Version [`2.5.0`](https://registry.terraform.io/modules/terraform-google-modules/bastion-host/google/2.5.0) released

**Pull request merged**
