### PR TITLE
fix: try() to fix index errors

### PR DESCRIPTION
**Pull request by astorozhevsky**
Fix the error in CI:
Error: Invalid index
service_account_email = var.service_account_email == "" ? google_service_account.bastion_host[0].email : var.service_account_email
google_service_account.bastion_host is empty tuple
The given key does not identify an element in this collection value: the collection has no elements.

image

refs: https://github.com/terraform-google-modules/terraform-google-bastion-host/issues/61

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@astorozhevsky
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by astorozhevsky** [comment]
@bharathkkb could you please review?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @astorozhevsky!

**Pull request merged**
