### PR TITLE
feat: add disk labels to bastion vm

### PR DESCRIPTION
**Pull request by hendrikiseke1979**
This PR adds the capability to configure the bastion host's disk labels.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@hendrikiseke1979
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.2xfHZnV35V/generate_docs/workspace/README.md
76a77
> | disk\_labels | Key-value map of labels to assign to the bastion host disk | `map(any)` | `{}` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@hendrikiseke1979
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@hendrikiseke1979
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — CHANGES_REQUESTED** [review]
Thanks for the contribution @hendrikiseke1979!

If you could please add usage of `disk_labels` to an example so this is covered by the CI: https://github.com/terraform-google-modules/terraform-google-bastion-host/blob/00a863ce0f37d69e6a9ac256aa358114a3a38bec/examples/simple_example/main.tf#L17

**Comment by comment-bot-dev** [comment]
@hendrikiseke1979
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by hendrikiseke1979** [comment]
@apeabody Thanks for reviewing, I added `disk_labels` to 'simple example'.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @hendrikiseke1979!

**Comment by apeabody** [comment]
> @apeabody Thanks for reviewing, I added `disk_labels` to 'simple example'.

Thanks - I see it was successfully applied in the INT check!

**Pull request merged**
