### PR TITLE
Optionally pass additional networks to the instance template

### PR DESCRIPTION
**Pull request by pwillis-eiq**
This passes through the `additional_networks` variable from https://github.com/terraform-google-modules/terraform-google-vm/tree/master/modules/instance_template . This allows using this module to build a bastion with more than one network interface.

Also passing in optional `service_account_email` and `metadata` as I'm using those too, to pass a pre-existing service account, and to pass additional instance metadata.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.1Wafm1J70r/generate_docs/workspace/README.md
72a73
> | additional\_networks | Additional network interface details for the instance template, if any. | <pre>list(object({<br>    network            = string<br>    subnetwork         = string<br>    subnetwork_project = string<br>    network_ip         = string<br>    access_config = list(object({<br>      nat_ip       = string<br>      network_tier = string<br>    }))<br>  }))</pre> | `[]` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/bastion-group/README.md /tmp/tmp.1Wafm1J70r/generate_docs/workspace/modules/bastion-group/README.md
75a76
> | additional\_networks | Additional network interface details for the instance template, if any. | <pre>list(object({<br>    network            = string<br>    subnetwork         = string<br>    subnetwork_project = string<br>    network_ip         = string<br>    access_config = list(object({<br>      nat_ip       = string<br>      network_tier = string<br>    }))<br>  }))</pre> | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
Success!
 The configuration is valid.
terraform_validate ./examples/bastion_group
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on ../../modules/bastion-group/main.tf line 36, in module "iap_bastion":
│
 
  36:   
additional_network
                 = var.additional_networks
│
 
│
 
An argument named "additional_network" is not expected here. Did you mean
│
 
"additional_networks"?
╵
terraform_validate ./examples/iap_tunneling
Success!
 The configuration is valid.
terraform_validate ./examples/simple_example
Success!
 The configuration is valid.
terraform_validate ./examples/two_service_example
Success!
 The configuration is valid.
terraform_validate ./modules/bastion-group
╷
│
 
Error: 
Unsupported argument
│
 
│
 
  on main.tf line 36, in module "iap_bastion":
│
 
  36:   
additional_network
                 = var.additional_networks
│
 
│
 
An argument named "additional_network" is not expected here. Did you mean
│
 
"additional_networks"?
╵
terraform_validate ./modules/iap-tunneling
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.GZTlxtJnMD/generate_docs/workspace/README.md
72a73
> | additional\_networks | Additional network interface details for the instance template, if any. | <pre>list(object({<br>    network            = string<br>    subnetwork         = string<br>    subnetwork_project = string<br>    network_ip         = string<br>    access_config = list(object({<br>      nat_ip       = string<br>      network_tier = string<br>    }))<br>  }))</pre> | `[]` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/bastion-group/README.md /tmp/tmp.GZTlxtJnMD/generate_docs/workspace/modules/bastion-group/README.md
75a76
> | additional\_networks | Additional network interface details for the instance template, if any. | <pre>list(object({<br>    network            = string<br>    subnetwork         = string<br>    subnetwork_project = string<br>    network_ip         = string<br>    access_config = list(object({<br>      nat_ip       = string<br>      network_tier = string<br>    }))<br>  }))</pre> | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/modules/bastion-group/README.md /tmp/tmp.js839z8UYM/generate_docs/workspace/modules/bastion-group/README.md
85a86
> | metadata | Key-value map of additional metadata to assign to the instances | `map(string)` | `{}` | no |
91a93
> | service\_account\_email | If set, the service account and its permissions will not be created. The service account being passed in should have at least the roles listed in the parent module `service_account_roles` variable so that logging and OS Login work as expected. | `string` | `""` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ```

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@pwillis-eiq
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @pwillis-eiq

**Pull request merged**
